In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers.core import Activation, Dense

Using TensorFlow backend.


In [4]:
# the four different states of the XOR gate
training_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], "float32")
training_data

array([[ 0.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  1.]], dtype=float32)

In [5]:
# the four expected results in the same order
target_data = np.array([[0], [1], [1], [0]], "float32")
target_data

array([[ 0.],
       [ 1.],
       [ 1.],
       [ 0.]], dtype=float32)

In [6]:
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

In [7]:
model.fit(training_data, target_data, nb_epoch=500, verbose=2)

/usr/local/lib/python3.5/dist-packages/keras/models.py:826: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/500
0s - loss: 0.2602 - binary_accuracy: 0.7500
Epoch 2/500
0s - loss: 0.2598 - binary_accuracy: 0.5000
Epoch 3/500
0s - loss: 0.2594 - binary_accuracy: 0.7500
Epoch 4/500
0s - loss: 0.2590 - binary_accuracy: 0.7500
Epoch 5/500
0s - loss: 0.2585 - binary_accuracy: 0.7500
Epoch 6/500
0s - loss: 0.2581 - binary_accuracy: 0.7500
Epoch 7/500
0s - loss: 0.2577 - binary_accuracy: 0.7500
Epoch 8/500
0s - loss: 0.2573 - binary_accuracy: 0.7500
Epoch 9/500
0s - loss: 0.2569 - binary_accuracy: 0.7500
Epoch 10/500
0s - loss: 0.2565 - binary_accuracy: 0.7500
Epoch 11/500
0s - loss: 0.2561 - binary_accuracy: 0.7500
Epoch 12/500
0s - loss: 0.2557 - binary_accuracy: 0.7500
Epoch 13/500
0s - loss: 0.2553 - binary_accuracy: 0.7500
Epoch 14/500
0s - loss: 0.2549 - binary_accuracy: 0.7500
Epoch 15/500
0s - loss: 0.2545 - binary_accuracy: 0.7500
Epoch 16/500
0s - loss: 0.2541 - binary_accuracy: 0.7500
Epoch 17/500
0s - loss: 0.2538 - binary_accuracy: 0.7500
Epoch 18/500
0s - loss: 0.2534 - binary_

In [8]:
print(model.predict(training_data).round())

[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]]


### Let's go crazy

In [28]:
training_data = np.array([[0, 0], [0, 1], [1, 0]], "float32")

In [29]:
target_data = np.array([[0], [1], [1]], "float32")

In [32]:
model.fit(training_data, target_data, nb_epoch=500, verbose=2)

/usr/local/lib/python3.5/dist-packages/keras/models.py:826: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 2/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 3/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 4/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 5/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 6/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 7/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 8/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 9/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 10/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 11/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 12/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 13/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 14/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 15/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 16/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 17/500
0s - loss: 0.0011 - binary_accuracy: 1.0000
Epoch 18/500
0s - loss: 0.0011 - binary_

In [33]:
print(model.predict(np.array([[0, 0], [0, 1], [1, 0], [1, 1]], "float32")).round())

[[ 0.]
 [ 1.]
 [ 1.]
 [ 1.]]
